version: '3.8'
services:
    postgres:
        image: postgres:alpine
        ports:
            - "35000:5432"
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: base

    api:
        # image: be-base
        build:
            dockerfile: Dockerfile
            context: .
        command: npm run start:dev
        depends_on:
            - postgres
        environment:
            # DATABASE_URL: postgres://postgres:postgres@postgres:5432/base
            POSTGRES_DB: base
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            NODE_ENV: development
            PORT: 3000
        ports:
            - "8000:3000"
    
  